.Dd May 11, 2026
.Dt RSYNCP 1
.Os
.Sh NAME
.Nm rsyncp
.Nd Progress wrapper for rsync
.Sh SYNOPSIS
.Nm rsyncp
.Oo
.Fl c Ar cookie |
.Fl x Ar str
.Op Fl x Ar str \&...
.Oc
.Op Fl r Ar rsync_name
.Op Fl i
.Fl -
.Ar rsync_arg_1
.Op Ar ... rsync_arg_n
.Sh DESCRIPTION
.Nm
wraps
.Nm rsync ,
displaying the percentage of files completed, and an estimate of the
time remaining, for repeated
.Nm rsync
invocations.
.Nm
does this by comparing the current
.Nm rsync
run to the previous run.
By definition, percentages and time remaining only appear from the second run
onwards.
In addition,
.Nm
shows the files sent (green) to and deleted on (red) the destination.
.Pp
In general, to use
.Nm
you need only change:
.Bd -literal -offset indent
rsync -arg1 -arg2 src1 src2 dst
.Ed
.Pp
to:
.Bd -literal -offset indent
rsyncp -- -arg1 -arg2 src1 src2 dst
.Ed
.Pp
The arguments to the right of the
.Fl -
are used to form a
.Dq cookie
that identifies this command.
If you use multiple different
.Nm rsync
invocations,
.Nm
treats them distinctly, giving appropriate time estimates for each.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar cookie
overrides the default cookie creation.
It is guaranteed that user defined cookies and
.Nm 's
default cookies cannot collide.
.Nm .
Mutually exclusive with
.Ar -x .
.It Fl i
Prints version number information to stdout and immediately exits.
.It Fl r Ar rsync_name
specifies the name of the
.Nm rsync
program.
Defaults to
.Qq rsync
if not specified.
.It Fl x Ar str
takes a string (including
.Ql -
and
.Ql --
prefixes) and excludes it from the cookie calculated from the
.Nm rsync
arguments to the right of the
.Fl - .
If, for example, you pass
.Fl -exclude-from=/random/path/to
and don't want the ever-changing random path to confuse the cookie, then
pass:
.Fl x
.Qq --exclude-from=/random/path/to
to
.Nm .
Mutually exclusive with
.Ar -c .
.El
.Pp
When
.Nm
calls
.Nm rsync
it will add several arguments to the call: the user will be warned if any
arguments they pass to
.Nm rsync
will collide with those passed by
.Nm .
.Sh STATE STORAGE
.Nm
stores state in:
.Bd -literal -offset indent
${XDG_STATE_HOME:-$HOME/.local/state}/rsyncp/
.Ed
.Pp
The state file name is a hash of the
.Nm rsync
arguments, after any
.Fl x
flags have been excluded.
Removing the state makes
.Nm
forget all previous runs.
.Sh LIMITATIONS
.Nm
estimates progress from the number of files
.Nm rsync
reports it has to check.
This means that the time remaining is only accurate when repeated invocations
have similar file counts and similar per-file checking costs.
.Sh SEE ALSO
.Nm rsync
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Laurence Tratt Aq Mt https://tratt.net/laurie/ .
